# Generated by Django 4.2 on 2023-11-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='category',
        ),
    ]
